include ../../Makefile.global

OBJ = string-utils.o bit-utils.o array-utils.o pseudo-list-utils.o type-utils.o packet-utils.o
LINKOBJ =  $(TSOBJ) $(CAPOBJ) $(OBJ)

all: $(OBJ)
	
clean:
	rm *.o || true
	
